spring: 
    profiles: 
        active:
           - dev
---
server:
  port: 8001
mybatis:
  type-aliases-package: com.hzit.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
   profiles: dev
   application:
    name: springcloud-eureka-dev
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: springcloud-dept-8001
    prefer-ip-address: true
info:
  app.name: springcloud-dept
  company.name: www.hzitxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$

---
server:
  port: 8001
mybatis:
  type-aliases-package: com.hzit.bean
  mapper-locations:
  - classpath:mybatis/mapper/**/*.xml
spring:
   profiles: test
   application:
    name: springcloud-eureka-test
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: org.gjt.mm.mysql.Driver
    url: jdbc:mysql://localhost:3306/school
    username: root
    password: root
    dbcp2:
      min-idle: 5
      initial-size: 5
      max-total: 5
      max-wait-millis: 200
eureka:
  client:
    service-url:
      # defaultZone: http://localhost:7001/eureka
      defaultZone: http://eureka7001.com:7001/eureka,http://eureka7002.com:7002/eureka,http://eureka7003.com:7003/eureka
  instance:
    instance-id: springcloud-dept-8001
    prefer-ip-address: true
info:
  app.name: springcloud-dept
  company.name: www.hzitxx.com
  build.artifactId: $project.artifactId$
  build.version: $project.version$